/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#006d44",
        "background": "#f8f9fb",
        "surface-container-low": "#f3f4f6",
        "surface-tint": "#006d44",
        "outline-variant": "#bbcabe",
        "on-tertiary-fixed-variant": "#004e5c",
        "surface-container-highest": "#e1e2e4",
        "outline": "#6c7b70",
        "on-background": "#191c1e",
        "on-secondary-fixed": "#221b00",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#002111",
        "surface": "#f8f9fb",
        "secondary": "#705d00",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#f0f1f3",
        "surface-dim": "#d9dadc",
        "secondary-fixed-dim": "#e9c400",
        "secondary-container": "#fdd400",
        "tertiary-fixed-dim": "#30d8fa",
        "primary-fixed-dim": "#46e099",
        "tertiary": "#00687a",
        "on-tertiary-fixed": "#001f26",
        "on-surface": "#191c1e",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#00c7e8",
        "surface-bright": "#f8f9fb",
        "primary-container": "#2dce89",
        "primary-fixed": "#68fdb3",
        "on-secondary-fixed-variant": "#544600",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "tertiary-fixed": "#acecff",
        "on-primary-fixed-variant": "#005232",
        "error-container": "#ffdad6",
        "inverse-surface": "#2e3132",
        "surface-container": "#edeef0",
        "surface-container-high": "#e7e8ea",
        "on-primary-container": "#005232",
        "on-secondary-container": "#6f5c00",
        "on-tertiary-container": "#004f5d",
        "inverse-primary": "#46e099",
        "surface-variant": "#e1e2e4",
        "on-surface-variant": "#3c4a41",
        "on-error": "#ffffff",
        "secondary-fixed": "#ffe170",
        "on-primary": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "24px",
        "sm": "12px",
        "xs": "4px",
        "xl": "64px",
        "md": "24px",
        "base": "8px",
        "lg": "48px",
        "margin": "32px"
      },
      fontFamily: {
        "h2": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "h3": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "h1": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "caption": ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        "h2": ["32px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-sm": ["14px", { lineHeight: "1", letterSpacing: "0.02em", fontWeight: "600" }],
        "h3": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "h1": ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "caption": ["12px", { lineHeight: "1.4", fontWeight: "400" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
